"""CarModel

Revision ID: 269d8a94004b
Revises: 8751f225c1e0
Create Date: 2019-10-27 21:42:37.073453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269d8a94004b'
down_revision = '8751f225c1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('engine_volume', sa.Integer(), nullable=True),
    sa.Column('engine_power', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_model_engine_power'), 'car_model', ['engine_power'], unique=False)
    op.create_index(op.f('ix_car_model_engine_volume'), 'car_model', ['engine_volume'], unique=False)
    op.create_index(op.f('ix_car_model_fuel_type'), 'car_model', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_car_model_manufacturer'), 'car_model', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_car_model_model'), 'car_model', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_model_model'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_manufacturer'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_fuel_type'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_engine_volume'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_engine_power'), table_name='car_model')
    op.drop_table('car_model')
    # ### end Alembic commands ###
